export const homeContent = {
  nav: {
    services: { id: "Layanan", en: "Services" },
    work: { id: "Karya", en: "Work" },
    pricing: { id: "Harga", en: "Pricing" },
    studio: { id: "Studio", en: "Studio" },
    talk: { id: "Mari bicara", en: "Let's talk" },
    open: { id: "Buka navigasi", en: "Open navigation" },
    close: { id: "Tutup navigasi", en: "Close navigation" },
  },
  hero: {
    eyebrow: { id: "Studio development digital independen", en: "Independent digital development studio" },
    availability: { id: "Tersedia untuk project pilihan", en: "Available for select projects" },
    lineOne: { id: "Produk digital", en: "Digital products" },
    accent: { id: "dibangun", en: "built" },
    lineTwo: { id: "dengan benar.", en: "properly." },
    description: {
      id: "Website, commerce, aplikasi, dan custom software dengan engineering dan security yang serius.",
      en: "Websites, commerce, applications, and custom software with serious engineering and security.",
    },
    primary: { id: "Mulai project", en: "Start a project" },
    secondary: { id: "Lihat karya", en: "Explore work" },
    featured: { id: "Project pilihan", en: "Featured project" },
  },
  about: {
    label: { id: "Tentang studio / 01", en: "About the studio / 01" },
    location: { id: "Depok + Jakarta\nBekerja secara global", en: "Depok + Jakarta\nWorking worldwide" },
    headlineBefore: { id: "Dari website sederhana hingga", en: "From simple websites to" },
    headlineAccent: { id: "platform digital custom.", en: "custom digital platforms." },
    description: {
      id: "Untuk bisnis, organisasi, dan ide yang membutuhkan produk digital berkualitas.",
      en: "For businesses, organizations, and ideas that need quality digital products.",
    },
    link: { id: "Tentang Hammad Studio", en: "About Hammad Studio" },
    capabilities: {
      id: ["Website", "E-Commerce", "Aplikasi Web", "Sistem Bisnis", "Automation & AI", "Custom Development"],
      en: ["Websites", "E-Commerce", "Web Applications", "Business Systems", "Automation & AI", "Custom Development"],
    },
  },
  whyItMatters: {
    label: { id: "Kenapa ini penting / 02", en: "Why it matters / 02" },
    headline: { id: "Website yang baik bukan sekadar", en: "A good website does more than" },
    accent: { id: "terlihat bagus.", en: "look good." },
    description: {
      id: "Ia membangun kepercayaan, menjelaskan value bisnis, dan membantu customer mengambil keputusan.",
      en: "It builds trust, explains business value, and helps customers make decisions.",
    },
    items: [
      { title: "Trust", description: { id: "Membuat bisnis terlihat kredibel sejak interaksi pertama.", en: "Makes the business feel credible from the first interaction." } },
      { title: "Clarity", description: { id: "Membantu customer memahami apa yang Anda tawarkan.", en: "Helps customers understand what you offer." } },
      { title: "Conversion", description: { id: "Mengubah perhatian menjadi inquiry, booking, atau transaksi.", en: "Turns attention into inquiries, bookings, or transactions." } },
      { title: "Foundation", description: { id: "Menjadi fondasi untuk SEO, campaign, commerce, dan sistem digital berikutnya.", en: "Becomes the foundation for SEO, campaigns, commerce, and future digital systems." } },
    ],
  },
  services: {
    label: { id: "Yang kami bangun / 03", en: "What we build / 03" },
    headline: { id: "Satu studio. Berbagai tingkat", en: "One studio. Different levels of" },
    accent: { id: "kompleksitas.", en: "complexity." },
    items: [
      {
        number: "01",
        title: { id: "Website", en: "Websites" },
        description: { id: "Website untuk brand, bisnis, organisasi, dan perusahaan.", en: "Websites for brands, businesses, organizations, and companies." },
        image: "/images/work/saudi-education-expo.webp",
      },
      {
        number: "02",
        title: { id: "E-Commerce", en: "E-Commerce" },
        description: { id: "Pengalaman belanja online yang profesional dari katalog hingga transaksi.", en: "Professional online shopping experiences from catalogue to transaction." },
        image: "/images/work/ajwa-date-store.webp",
      },
      {
        number: "03",
        title: { id: "Web Application", en: "Web Applications" },
        description: { id: "Aplikasi berbasis workflow untuk customer, member, admin, dan tim internal.", en: "Workflow-based applications for customers, members, admins, and internal teams." },
        image: "/images/work/operations-dashboard.webp",
      },
      {
        number: "04",
        title: { id: "Business System", en: "Business Systems" },
        description: { id: "Sistem custom yang membuat operasional bisnis lebih terstruktur.", en: "Custom systems that bring structure to business operations." },
        image: "/images/work/operations-dashboard.webp",
      },
      {
        number: "05",
        title: { id: "Automation & AI", en: "Automation & AI" },
        description: { id: "Automation untuk mengurangi pekerjaan repetitif tanpa menghilangkan peran manusia.", en: "Automation that reduces repetitive work without removing the human role." },
        image: "/images/work/operations-dashboard.webp",
      },
      {
        number: "06",
        title: { id: "Custom Development", en: "Custom Development" },
        description: { id: "Development untuk produk, platform, dan kebutuhan yang tidak cocok dengan paket standar.", en: "Development for products, platforms, and needs that do not fit standard packages." },
        image: "/images/work/saudi-education-expo.webp",
      },
    ],
  },
  security: {
    label: { id: "Security-driven development", en: "Security-driven development" },
    headline: { id: "Security adalah bagian dari", en: "Security is part of the" },
    accent: { id: "fondasi.", en: "foundation." },
    description: {
      id: "Background kami di software engineering dan security research membuat security dipikirkan sejak awal development—bukan setelah produk selesai.",
      en: "Our background in software engineering and security research means security is considered from the start—not after the product is finished.",
    },
    note: {
      id: "Kami tidak menjanjikan sistem yang tidak mungkin diretas. Kami membangun software dengan security-conscious engineering practices sejak awal.",
      en: "We do not promise an impossible-to-hack system. We build software with security-conscious engineering practices from day one.",
    },
    practices: {
      id: ["Secure Authentication", "Access Control", "API & Data Protection", "Security Review"],
      en: ["Secure Authentication", "Access Control", "API & Data Protection", "Security Review"],
    },
    link: { id: "Tentang pendekatan security kami", en: "About our security approach" },
  },
  principles: {
    label: { id: "Prinsip development", en: "Development principles" },
    headline: { id: "Modern tools.", en: "Modern tools." },
    accent: { id: "Standar tetap tinggi.", en: "Standards stay high." },
    description: {
      id: "Kami menggunakan tools modern dan AI-assisted development untuk mempercepat proses, tetapi architecture, logic, security, usability, dan maintainability tetap melalui review manusia.",
      en: "We use modern tools and AI-assisted development to move faster, while architecture, logic, security, usability, and maintainability remain subject to human review.",
    },
    items: [
      { title: { id: "Quality over shortcuts", en: "Quality over shortcuts" }, description: { id: "Kecepatan penting, tetapi bukan dengan mengorbankan fondasi produk.", en: "Speed matters, but never at the cost of the product's foundations." } },
      { title: { id: "Built for real use", en: "Built for real use" }, description: { id: "Performance, admin experience, error handling, data, dan kebutuhan setelah launch ikut dipikirkan.", en: "Performance, admin experience, error handling, data, and post-launch realities are considered." } },
      { title: { id: "Simple when possible", en: "Simple when possible" }, description: { id: "Complexity hanya ditambahkan ketika benar-benar memberi value.", en: "Complexity is introduced only when it creates real value." } },
      { title: { id: "Scalable when needed", en: "Scalable when needed" }, description: { id: "Dibangun untuk kebutuhan hari ini tanpa menutup kemungkinan berkembang besok.", en: "Built for today's needs without closing the door on tomorrow's growth." } },
    ],
  },
  work: {
    label: { id: "Karya pilihan / 05", en: "Selected work / 05" },
    headline: { id: "Produk yang bekerja", en: "Work that" },
    accent: { id: "di dunia nyata.", en: "works hard." },
    all: { id: "Semua project", en: "All projects" },
    categories: {
      event: { id: "Platform event", en: "Event platform" },
      operations: { id: "Sistem operasional", en: "Operations system" },
      commerce: { id: "E-Commerce", en: "E-Commerce" },
    },
  },
  pricing: {
    label: { id: "Titik awal harga / 06", en: "Starting prices / 06" },
    headline: { id: "Mulai dari kebutuhan yang", en: "Start with the right" },
    accent: { id: "tepat.", en: "scope." },
    description: { id: "Setiap project memiliki kebutuhan berbeda. Harga final ditentukan berdasarkan scope dan kompleksitas.", en: "Every project has different requirements. Final pricing is determined by scope and complexity." },
    package: { id: "Paket", en: "Package" },
    starting: { id: "Mulai dari", en: "Starting from" },
    detail: { id: "Lihat paket lengkap", en: "View complete packages" },
    items: [
      { title: { id: "Website", en: "Website" }, price: "Rp 2,5 juta" },
      { title: { id: "E-Commerce", en: "E-Commerce" }, price: "Rp 5 juta" },
      { title: { id: "Web Application", en: "Web Application" }, price: "Rp 10 juta" },
      { title: { id: "Automation & AI", en: "Automation & AI" }, price: "Rp 5 juta" },
      { title: { id: "Business System", en: "Business System" }, price: "Rp 15 juta" },
      { title: { id: "Custom Development", en: "Custom Development" }, price: "Rp 15 juta" },
    ],
  },
  footer: {
    prompt: { id: "Punya project?", en: "Have a project?" },
    makeReal: { id: "Mari wujudkan", en: "Let's make it real" },
    lets: { id: "Mari", en: "Let's" },
    talk: { id: "bicara.", en: "talk." },
    description: { id: "Website, commerce, aplikasi, sistem, dan automation dengan quality engineering dan security dalam setiap prosesnya.", en: "Websites, commerce, applications, systems, and automation with quality engineering and security in every process." },
    available: { id: "Tersedia untuk project pilihan", en: "Available for select projects" },
    newBusiness: { id: "Project baru", en: "New business" },
    closing: { id: "Teknologi harus menyelesaikan masalah, bukan menciptakan complexity baru.", en: "Technology should solve problems, not create new complexity." },
  },
} as const;
