export const homeContent = {
  nav: {
    services: { id: "Layanan", en: "Services" },
    work: { id: "Karya", en: "Work" },
    pricing: { id: "Harga", en: "Pricing" },
    studio: { id: "Studio", en: "Studio" },
    talk: { id: "Mari bicara", en: "Let's talk" },
    open: { id: "Buka navigasi", en: "Open navigation" },
    close: { id: "Tutup navigasi", en: "Close navigation" },
  },
  hero: {
    eyebrow: { id: "Studio development digital independen", en: "Independent digital development studio" },
    availability: { id: "Tersedia untuk project pilihan", en: "Available for select projects" },
    lineOne: { id: "Produk digital", en: "Digital products" },
    accent: { id: "dibangun", en: "built" },
    lineTwo: { id: "dengan benar.", en: "properly." },
    description: {
      id: "Kami membangun website, e-commerce, aplikasi web, automation, dan sistem bisnis custom dengan fondasi teknis yang kuat.",
      en: "We build websites, e-commerce, web applications, automation, and custom business systems on strong technical foundations.",
    },
    primary: { id: "Mulai project", en: "Start a project" },
    secondary: { id: "Lihat karya", en: "Explore work" },
    featured: { id: "Project pilihan", en: "Featured project" },
  },
  about: {
    label: { id: "Tentang studio / 01", en: "About the studio / 01" },
    location: { id: "Depok + Jakarta\nBekerja secara global", en: "Depok + Jakarta\nWorking worldwide" },
    headlineBefore: { id: "Dari website sederhana hingga", en: "From simple websites to" },
    headlineAccent: { id: "platform digital custom.", en: "custom digital platforms." },
    description: {
      id: "Hammad Studio membantu individu, bisnis, organisasi, dan perusahaan membangun produk digital yang profesional, cepat, scalable, aman, dan siap digunakan dalam jangka panjang.",
      en: "Hammad Studio helps individuals, businesses, organizations, and companies build professional, fast, scalable, secure digital products made for long-term use.",
    },
    link: { id: "Kenal lebih dekat", en: "Meet the studio" },
    capabilities: {
      id: ["Website", "E-Commerce", "Aplikasi Web", "Sistem Bisnis", "Automation & AI", "Custom Development"],
      en: ["Websites", "E-Commerce", "Web Applications", "Business Systems", "Automation & AI", "Custom Development"],
    },
  },
  services: {
    label: { id: "Yang kami bangun / 02", en: "What we build / 02" },
    headline: { id: "Satu studio. Berbagai tingkat", en: "One studio. Different levels of" },
    accent: { id: "kompleksitas.", en: "complexity." },
    items: [
      {
        number: "01",
        title: { id: "Website", en: "Websites" },
        description: { id: "Landing page, portfolio, company profile, corporate, event, CMS, SEO foundation, analytics, dan performance optimization.", en: "Landing pages, portfolios, company profiles, corporate and event sites, CMS, SEO foundations, analytics, and performance optimization." },
        image: "/images/work/saudi-education-expo.webp",
      },
      {
        number: "02",
        title: { id: "E-Commerce", en: "E-Commerce" },
        description: { id: "Katalog, cart, checkout, payment gateway, QRIS, order management, inventory, invoice, shipping, dan sales dashboard.", en: "Catalogues, cart, checkout, payment gateways, QRIS, order management, inventory, invoices, shipping, and sales dashboards." },
        image: "/images/work/ajwa-date-store.webp",
      },
      {
        number: "03",
        title: { id: "Web Application", en: "Web Applications" },
        description: { id: "Customer portal, member area, admin dashboard, booking, registrasi, ticketing, QR check-in, reporting, dan data platform.", en: "Customer portals, member areas, admin dashboards, booking, registration, ticketing, QR check-in, reporting, and data platforms." },
        image: "/images/work/operations-dashboard.webp",
      },
      {
        number: "04",
        title: { id: "Business System", en: "Business Systems" },
        description: { id: "CRM, lead dan order management, customer database, approval workflow, role & permission, reporting, dan dashboard operasional.", en: "CRM, lead and order management, customer databases, approval workflows, roles and permissions, reporting, and operational dashboards." },
        image: "/images/work/operations-dashboard.webp",
      },
      {
        number: "05",
        title: { id: "Automation & AI", en: "Automation & AI" },
        description: { id: "AI customer service, WhatsApp automation, lead qualification, follow-up, notification, document generation, dan workflow automation.", en: "AI customer service, WhatsApp automation, lead qualification, follow-up, notifications, document generation, and workflow automation." },
        image: "/images/work/operations-dashboard.webp",
      },
      {
        number: "06",
        title: { id: "Custom Development", en: "Custom Development" },
        description: { id: "SaaS, marketplace, API, integrasi pihak ketiga, multi-role application, MVP, dan platform digital dengan workflow khusus.", en: "SaaS, marketplaces, APIs, third-party integrations, multi-role applications, MVPs, and specialized digital platforms." },
        image: "/images/work/saudi-education-expo.webp",
      },
    ],
  },
  security: {
    label: { id: "Security-driven development", en: "Security-driven development" },
    headline: { id: "Security adalah bagian dari", en: "Security is part of the" },
    accent: { id: "fondasi.", en: "foundation." },
    description: {
      id: "Background engineering kami dekat dengan cybersecurity dan security research. Karena itu, security dipertimbangkan sejak proses development, bukan baru setelah sistem selesai.",
      en: "Our engineering background is closely connected to cybersecurity and security research. Security is considered from the start, not added after the system is finished.",
    },
    note: {
      id: "Kami tidak menjanjikan sistem yang tidak mungkin diretas. Kami membangun software dengan security-conscious engineering practices sejak awal.",
      en: "We do not promise an impossible-to-hack system. We build software with security-conscious engineering practices from day one.",
    },
    practices: {
      id: ["Secure authentication", "Role & access control", "Input & API protection", "Secure session handling", "Audit logging", "Dependency review", "Rate limiting", "Error & activity monitoring"],
      en: ["Secure authentication", "Role & access control", "Input & API protection", "Secure session handling", "Audit logging", "Dependency review", "Rate limiting", "Error & activity monitoring"],
    },
  },
  principles: {
    label: { id: "Prinsip development", en: "Development principles" },
    headline: { id: "Modern tools.", en: "Modern tools." },
    accent: { id: "Standar tetap tinggi.", en: "Standards stay high." },
    description: {
      id: "Kami menggunakan tools modern dan AI-assisted development untuk mempercepat proses, tetapi architecture, logic, security, usability, dan maintainability tetap melalui review manusia.",
      en: "We use modern tools and AI-assisted development to move faster, while architecture, logic, security, usability, and maintainability remain subject to human review.",
    },
    items: [
      { title: { id: "Quality over shortcuts", en: "Quality over shortcuts" }, description: { id: "Kecepatan penting, tetapi bukan dengan mengorbankan fondasi produk.", en: "Speed matters, but never at the cost of the product's foundations." } },
      { title: { id: "Built for real use", en: "Built for real use" }, description: { id: "Performance, admin experience, error handling, data, dan kebutuhan setelah launch ikut dipikirkan.", en: "Performance, admin experience, error handling, data, and post-launch realities are considered." } },
      { title: { id: "Simple when possible", en: "Simple when possible" }, description: { id: "Complexity hanya ditambahkan ketika benar-benar memberi value.", en: "Complexity is introduced only when it creates real value." } },
      { title: { id: "Scalable when needed", en: "Scalable when needed" }, description: { id: "Dibangun untuk kebutuhan hari ini tanpa menutup kemungkinan berkembang besok.", en: "Built for today's needs without closing the door on tomorrow's growth." } },
    ],
  },
  work: {
    label: { id: "Karya pilihan / 05", en: "Selected work / 05" },
    headline: { id: "Produk yang bekerja", en: "Work that" },
    accent: { id: "di dunia nyata.", en: "works hard." },
    all: { id: "Semua project", en: "All projects" },
    categories: {
      event: { id: "Platform event", en: "Event platform" },
      operations: { id: "Sistem operasional", en: "Operations system" },
      commerce: { id: "E-Commerce", en: "E-Commerce" },
    },
  },
  pricing: {
    label: { id: "Paket layanan / 06", en: "Service packages / 06" },
    headline: { id: "Mulai sesuai kebutuhan.", en: "Start with what you need." },
    accent: { id: "Berkembang saat dibutuhkan.", en: "Grow when needed." },
    description: { id: "Angka ini adalah titik awal. Scope, kompleksitas, dan integrasi menentukan investasi final.", en: "These are starting points. Scope, complexity, and integrations determine the final investment." },
    package: { id: "Paket", en: "Package" },
    starting: { id: "Mulai dari", en: "Starting from" },
    items: [
      { title: "Website", price: "Rp3.5M", description: { id: "Portfolio, landing page, company profile, dan business website.", en: "Portfolios, landing pages, company profiles, and business websites." } },
      { title: "Commerce", price: "Rp9.5M", description: { id: "Platform penjualan dengan katalog, payment, dan order management.", en: "Sales platforms with catalogues, payments, and order management." } },
      { title: "Application", price: "Rp12.5M", description: { id: "Dashboard, portal, booking, registrasi, dan member platform.", en: "Dashboards, portals, booking, registration, and member platforms." } },
      { title: "System", price: "Rp12.5M", description: { id: "CRM, operations, internal tools, reporting, dan custom workflow.", en: "CRM, operations, internal tools, reporting, and custom workflows." } },
      { title: "Automation", price: "Rp5M", description: { id: "Customer service, follow-up, notification, dan workflow automation.", en: "Customer service, follow-up, notifications, and workflow automation." } },
      { title: "Custom", price: "Rp18M", description: { id: "SaaS, marketplace, specialized platform, dan custom software.", en: "SaaS, marketplaces, specialized platforms, and custom software." } },
    ],
  },
  footer: {
    prompt: { id: "Punya project?", en: "Have a project?" },
    makeReal: { id: "Mari wujudkan", en: "Let's make it real" },
    lets: { id: "Mari", en: "Let's" },
    talk: { id: "bicara.", en: "talk." },
    description: { id: "Website, commerce, aplikasi, sistem, dan automation dengan quality engineering dan security dalam setiap prosesnya.", en: "Websites, commerce, applications, systems, and automation with quality engineering and security in every process." },
    available: { id: "Tersedia untuk project pilihan", en: "Available for select projects" },
    newBusiness: { id: "Project baru", en: "New business" },
    closing: { id: "Teknologi harus menyelesaikan masalah, bukan menciptakan complexity baru.", en: "Technology should solve problems, not create new complexity." },
  },
} as const;
