import { companyFaqs, umkmFaqs } from "./seo-landing-content";

export type ExpansionLanding = {
  slug: string;
  title: string;
  description: string;
  eyebrow: string;
  hero: string;
  intro: string;
  audience: string;
  outcomes: readonly string[];
  deliverables: readonly string[];
  proofs: readonly { name: string; detail: string; href: string }[];
  faqs: readonly { question: string; answer: string }[];
  startingPrice: string;
  proofLabel?: string;
  proofTitle?: string;
  indexable?: boolean;
};

export const solutionLandings = {
  "umkm/toko-online": {
    slug: "umkm/toko-online",
    title: "Jasa Pembuatan Website Toko Online UMKM",
    description: "Website toko online untuk UMKM dengan katalog produk, WhatsApp, cart, checkout, promo, dan pengelolaan produk sesuai kebutuhan bisnis.",
    eyebrow: "TOKO ONLINE UNTUK UMKM",
    hero: "Toko online milik brand, bukan sekadar etalase di marketplace.",
    intro: "Website toko online membantu UMKM menyajikan produk dengan identitas sendiri, mengarahkan order ke WhatsApp atau checkout, dan membangun database serta pengalaman customer yang lebih terkontrol.",
    audience: "Cocok untuk bisnis makanan, fashion, merchandise, frozen food, dan brand lokal yang ingin melengkapi marketplace serta media sosial dengan storefront resmi.",
    outcomes: ["Produk tersusun dalam katalog yang mudah dicari.", "Order dapat diarahkan ke WhatsApp atau checkout.", "Promo dan presentasi brand tidak dibatasi marketplace.", "Analytics membantu melihat produk dan jalur yang digunakan customer."],
    deliverables: ["Struktur kategori dan katalog produk", "Halaman produk responsif", "Cart atau order via WhatsApp", "Promo dan featured products", "CMS pengelolaan produk", "Analytics dan event order", "SEO foundation untuk kategori utama", "Deployment dan handover"],
    proofs: [{ name: "Shofi Frozen", detail: "Katalog frozen food dengan pencarian, wishlist, promo, cart, dan checkout WhatsApp.", href: "/work/shofi-frozen" }, { name: "CPX Jersey", detail: "Commerce sportswear dengan katalog, cart, custom order, dan integrasi marketplace.", href: "/work/cpx-jersey" }, { name: "Website UMKM", detail: "Lihat fondasi website untuk bisnis kecil dan brand berkembang.", href: "/jasa-website-umkm" }],
    faqs: umkmFaqs,
    startingPrice: "Commerce mulai Rp 2,299 juta. Full payment gateway tersedia melalui Commerce Pro mulai Rp 3,799 juta.",
  },
  "umkm/landing-page-produk": {
    slug: "umkm/landing-page-produk",
    title: "Jasa Landing Page Produk untuk UMKM",
    description: "Landing page produk untuk campaign UMKM yang menghubungkan iklan, penawaran, bukti, FAQ, dan WhatsApp dalam satu alur conversion.",
    eyebrow: "LANDING PAGE PRODUK",
    hero: "Bawa traffic iklan ke halaman yang fokus menjelaskan dan menjual.",
    intro: "Landing page produk menyatukan value proposition, visual, benefit, bukti, objection handling, dan CTA dalam satu journey yang dapat diukur—bukan mengirim calon customer ke profil yang penuh distraksi.",
    audience: "Untuk UMKM dan brand yang menjalankan campaign Meta, TikTok, Google, influencer, atau peluncuran produk dan membutuhkan destination page khusus.",
    outcomes: ["Pesan campaign tetap konsisten dari iklan ke halaman.", "Customer mendapat konteks sebelum membuka WhatsApp.", "Klik CTA dan form dapat diukur sebagai conversion.", "Halaman dapat diuji dan dikembangkan untuk campaign berikutnya."],
    deliverables: ["Campaign discovery", "Copy hierarchy dan objection handling", "Responsive landing page", "WhatsApp atau lead form", "Analytics dan conversion event", "Performance optimization", "Metadata dan indexability sesuai campaign", "Deployment"],
    proofs: [{ name: "NaikLevel AI", detail: "Landing dan commerce flow untuk produk edukasi AI dengan pembayaran serta konfirmasi.", href: "/work/naiklevel-ai" }, { name: "Shofi Frozen", detail: "Product discovery dan order flow untuk bisnis frozen food.", href: "/work/shofi-frozen" }, { name: "Harga Website", detail: "Bandingkan titik awal paket yang tersedia.", href: "/harga-website" }],
    faqs: umkmFaqs,
    startingPrice: "Website mulai Rp 499 ribu untuk maksimal 5 halaman utama. Copywriting, foto produk, dan kebutuhan campaign mengikuti scope.",
  },
  "perusahaan/sistem-custom-dashboard": {
    slug: "perusahaan/sistem-custom-dashboard",
    title: "Jasa Pembuatan Dashboard dan Sistem Custom Perusahaan",
    description: "Pengembangan dashboard, portal, dan sistem web custom untuk workflow, data, role pengguna, approval, serta reporting perusahaan.",
    eyebrow: "SISTEM CUSTOM PERUSAHAAN",
    hero: "Sistem yang mengikuti workflow bisnis, bukan memaksa bisnis mengikuti template.",
    intro: "Dashboard dan sistem custom dibangun ketika spreadsheet, chat, dan software umum tidak lagi cukup menangani role, data, approval, serta kebutuhan operasional perusahaan.",
    audience: "Untuk perusahaan dan organisasi yang membutuhkan portal pelanggan, dashboard operasional, administrasi, booking, reporting, atau integrasi dengan layanan yang sudah digunakan.",
    outcomes: ["Data dan aktivitas penting lebih terstruktur.", "Role serta permission mengikuti tanggung jawab tim.", "Workflow repetitif dapat dikurangi atau diautomasi.", "Sistem dapat dikembangkan bertahap mengikuti prioritas bisnis."],
    deliverables: ["Discovery dan workflow mapping", "Requirement serta acceptance criteria", "Architecture dan data model", "Authentication, role, dan permission", "Dashboard serta operational flow", "API dan integrasi", "Security review dan QA", "Deployment, dokumentasi, dan handover"],
    proofs: [{ name: "StudyShare", detail: "Platform dengan akun, kontribusi materi, kategori, dan discovery content.", href: "/work/studyshare" }, { name: "Masjid Raya Puri Telukjambe", detail: "Platform layanan, jadwal, donasi, livestream, dan booking fasilitas.", href: "/work/masjid-raya-puri-telukjambe" }, { name: "Web Application", detail: "Lihat cakupan umum aplikasi web Hammad Studio.", href: "/jasa-web-app" }],
    faqs: companyFaqs,
    startingPrice: "Business Apps dimulai dari Booking Rp 2,499 juta atau Business Rp 2,999 juta. Operational mulai Rp 5,999 juta. Estimasi mengikuti modul dan integrasi.",
  },
  "perusahaan/maintenance-support": {
    slug: "perusahaan/maintenance-support",
    title: "Jasa Maintenance Website Perusahaan",
    description: "Maintenance website perusahaan untuk update teknis, monitoring, backup, perbaikan bug, perubahan konten, dan pengembangan berkelanjutan.",
    eyebrow: "MAINTENANCE & SUPPORT",
    hero: "Website perusahaan membutuhkan ownership setelah hari peluncuran.",
    intro: "Maintenance menjaga website tetap aman, kompatibel, terukur, dan relevan. Scope dukungan dapat mencakup monitoring, dependency update, backup, bug fixing, content update, serta improvement terencana.",
    audience: "Untuk perusahaan yang membutuhkan PIC teknis jelas, ritme pemeliharaan, dokumentasi, dan response time yang disepakati sesuai tingkat kepentingan website.",
    outcomes: ["Masalah teknis memiliki jalur eskalasi yang jelas.", "Update dependency dan risiko keamanan dipantau.", "Konten serta improvement tidak menumpuk tanpa owner.", "Perubahan dapat direncanakan dengan scope dan prioritas transparan."],
    deliverables: ["Technical health check", "Dependency dan security update", "Backup serta recovery review", "Bug fixing berdasarkan prioritas", "Content update allowance", "Performance monitoring", "Monthly activity summary", "SLA sesuai paket dan kebutuhan"],
    proofs: [{ name: "Solivate", detail: "Website teknologi dengan kebutuhan presentasi layanan yang terus berkembang.", href: "/work/solivate" }, { name: "ADD Logistik", detail: "Website corporate yang menjadi rujukan layanan perusahaan.", href: "/work/add-logistik" }, { name: "Redesign Website", detail: "Audit dan perbaikan menyeluruh untuk website yang sudah tertinggal.", href: "/redesign-website" }],
    faqs: companyFaqs,
    startingPrice: "Maintenance disusun berdasarkan response time, frekuensi update, dan kompleksitas stack. Audit awal dilakukan sebelum komitmen dukungan.",
  },
} as const satisfies Record<string, ExpansionLanding>;

export const industryLandings = {
  travel: {
    slug: "travel",
    title: "Jasa Website Travel Umrah dan Haji",
    description: "Website travel Umrah dan Haji yang membangun kepercayaan melalui paket, legal information, edukasi, galeri, konsultasi, dan alur pendaftaran.",
    eyebrow: "WEBSITE INDUSTRI TRAVEL",
    hero: "Bangun kepercayaan calon jamaah sebelum percakapan pertama.",
    intro: "Website travel Umrah dan Haji perlu menyatukan informasi paket, layanan, kredibilitas, edukasi, dokumentasi perjalanan, serta jalur konsultasi dalam pengalaman yang menenangkan dan mudah dipahami.",
    audience: "Untuk travel Umrah, Haji, dan wisata halal yang ingin memiliki pusat informasi resmi di luar media sosial serta mempermudah journey calon jamaah.",
    outcomes: ["Paket dan fasilitas lebih mudah dibandingkan.", "Legalitas serta trust signals mendapat ruang yang jelas.", "Artikel dan FAQ membantu menjawab kekhawatiran jamaah.", "Konsultasi dan pendaftaran diarahkan melalui journey yang terukur."],
    deliverables: ["Paket dan departure information", "Profil, legalitas, dan trust signals", "Galeri serta dokumentasi", "Artikel edukasi dan FAQ", "Konsultasi dan registration flow", "WhatsApp atau lead form", "CMS dan SEO foundation", "Analytics serta conversion tracking"],
    proofs: [{ name: "JamWisata", detail: "Website travel dengan package finder, jadwal, katalog perjalanan, galeri, testimoni, dan konsultasi.", href: "/work/jamwisata" }, { name: "Sahabat Qolbu", detail: "Website travel dengan fokus pada trust, paket, konsultasi, dan pendaftaran.", href: "/work/sahabat-qolbu" }, { name: "Nusuk Haromain Indonesia", detail: "Website premium dengan paket, artikel, galeri, dan journey calon jamaah.", href: "/work/nusuk-haromain-indonesia" }],
    faqs: companyFaqs,
    startingPrice: "Website travel dimulai dari scope company profile; katalog paket, CMS artikel, pendaftaran, dan integrasi disesuaikan kebutuhan operasional.",
  },
  "umkm-kuliner": {
    slug: "umkm-kuliner",
    title: "Jasa Website UMKM Kuliner dan Frozen Food",
    description: "Website untuk UMKM kuliner dengan katalog menu atau produk, promo, lokasi, WhatsApp order, dan pengelolaan konten yang sederhana.",
    eyebrow: "WEBSITE UMKM KULINER",
    hero: "Buat produk kuliner lebih mudah ditemukan, dipilih, dan dipesan.",
    intro: "Website kuliner memberi bisnis ruang resmi untuk menyajikan menu, katalog, harga, promo, lokasi, cara penyimpanan, dan alur pemesanan tanpa bergantung pada format media sosial.",
    audience: "Untuk frozen food, catering, bakery, coffee shop, restoran, dan produsen makanan yang membutuhkan katalog serta jalur order yang lebih rapi.",
    outcomes: ["Menu dan produk tersusun dalam kategori yang jelas.", "Customer dapat memesan melalui WhatsApp dengan konteks.", "Promo, lokasi, dan informasi bisnis mudah ditemukan.", "Brand memiliki halaman resmi untuk campaign dan pencarian Google."],
    deliverables: ["Katalog menu atau produk", "Kategori dan pencarian", "Promo dan featured items", "WhatsApp order flow", "Maps dan informasi outlet", "CMS sederhana", "SEO foundation", "Analytics dan tracking order"],
    proofs: [{ name: "Shofi Frozen", detail: "Storefront frozen food dengan katalog, pencarian, wishlist, promo, cart, dan checkout WhatsApp.", href: "/work/shofi-frozen" }, { name: "Toko Online UMKM", detail: "Lihat cakupan storefront milik brand.", href: "/solusi/umkm/toko-online" }, { name: "Website UMKM", detail: "Fondasi website untuk bisnis lokal dan brand berkembang.", href: "/jasa-website-umkm" }],
    faqs: umkmFaqs,
    startingPrice: "Website mulai Rp 499 ribu; CMS Rp 899 ribu; Commerce mulai Rp 2,299 juta.",
  },
  pendidikan: {
    slug: "pendidikan",
    title: "Jasa Website dan Platform Pendidikan",
    description: "Website sekolah, lembaga pendidikan, course, dan platform belajar dengan informasi program, materi, registrasi, akun, serta pengelolaan konten.",
    eyebrow: "WEBSITE INDUSTRI PENDIDIKAN",
    hero: "Informasi pendidikan yang jelas, platform belajar yang mudah digunakan.",
    intro: "Kebutuhan pendidikan dapat dimulai dari website institusi hingga platform dengan akun, materi, kontribusi, registrasi, dan dashboard. Arsitektur dipilih berdasarkan pengguna serta workflow nyata.",
    audience: "Untuk sekolah, lembaga kursus, komunitas belajar, penyelenggara pelatihan, dan produk edukasi digital.",
    outcomes: ["Program dan informasi institusi mudah dipahami.", "Materi dapat dikelola dan ditemukan secara terstruktur.", "Registrasi atau pembelian memiliki journey yang jelas.", "Platform dapat berkembang mengikuti role serta kebutuhan belajar."],
    deliverables: ["Profil institusi dan program", "CMS berita atau materi", "Registrasi dan form", "Akun serta role bila diperlukan", "Search dan content discovery", "Pembayaran untuk produk edukasi", "Analytics dan SEO foundation", "Security review dan handover"],
    proofs: [{ name: "StudyShare", detail: "Platform kolaboratif dengan akun, catatan, kategori mata pelajaran, dan discovery.", href: "/work/studyshare" }, { name: "NaikLevel AI", detail: "Website produk edukasi AI dengan commerce dan pembayaran manual.", href: "/work/naiklevel-ai" }, { name: "Web Application", detail: "Cakupan aplikasi web untuk role, data, dan workflow.", href: "/jasa-web-app" }],
    faqs: companyFaqs,
    startingPrice: "Website mulai Rp 499 ribu dan CMS mulai Rp 899 ribu. Sistem dengan akun serta workflow mengikuti produk Business Apps.",
  },
  fashion: {
    slug: "fashion",
    title: "Jasa Website Fashion dan Brand Apparel",
    description: "Website fashion dan apparel dengan katalog koleksi, varian produk, lookbook, custom order, marketplace, dan commerce flow milik brand.",
    eyebrow: "WEBSITE FASHION & APPAREL",
    hero: "Tampilkan koleksi dan karakter brand tanpa batasan layout marketplace.",
    intro: "Website fashion membantu brand menyatukan campaign, koleksi, ukuran, varian, lookbook, ready stock, custom order, dan jalur pembelian dalam pengalaman visual milik sendiri.",
    audience: "Untuk brand pakaian, jersey, modest fashion, accessories, dan apparel custom yang ingin membangun storefront resmi serta melengkapi marketplace.",
    outcomes: ["Koleksi dan kategori lebih mudah dieksplorasi.", "Visual brand konsisten dari campaign hingga produk.", "Varian, ukuran, dan custom order mendapat alur yang jelas.", "Traffic dapat diarahkan ke checkout, WhatsApp, atau marketplace."],
    deliverables: ["Collection dan category architecture", "Product detail dan variant", "Size guide dan product information", "Lookbook atau campaign", "Cart, WhatsApp, atau marketplace flow", "CMS produk", "Analytics dan commerce event", "SEO foundation"],
    proofs: [{ name: "CPX Jersey", detail: "Commerce sportswear dengan katalog, kategori olahraga, cart, custom order, dan marketplace.", href: "/work/cpx-jersey" }, { name: "Toko Online UMKM", detail: "Cakupan storefront, katalog, dan order flow milik brand.", href: "/solusi/umkm/toko-online" }, { name: "E-Commerce", detail: "Lihat layanan commerce untuk kebutuhan transaksi yang lebih lengkap.", href: "/services/e-commerce" }],
    faqs: umkmFaqs,
    startingPrice: "Website katalog fashion mulai mengikuti scope commerce sederhana. Varian, inventory, pembayaran, dan custom order dihitung sesuai workflow.",
  },
  manufaktur: {
    slug: "manufaktur",
    title: "Jasa Website Perusahaan Manufaktur",
    description: "Website perusahaan manufaktur untuk menjelaskan kapabilitas produksi, fasilitas, sertifikasi valid, produk, industri, dokumentasi, dan RFQ B2B.",
    eyebrow: "WEBSITE PERUSAHAAN MANUFAKTUR",
    hero: "Ubah kapabilitas produksi menjadi informasi yang mudah dinilai buyer B2B.",
    intro: "Website manufaktur perlu membantu procurement dan calon partner memahami produk, kapasitas, proses, industri yang dilayani, quality control, dokumen, serta jalur request for quotation.",
    audience: "Untuk produsen dan perusahaan manufaktur yang membutuhkan company profile teknis, katalog, dokumen, dan inquiry B2B tanpa membuat klaim sertifikasi yang tidak dapat diverifikasi.",
    outcomes: ["Kapabilitas dan product range lebih mudah dipahami.", "Buyer dapat menemukan dokumen dan jalur RFQ.", "Informasi fasilitas serta quality process tersusun jelas.", "Tim sales memiliki referensi resmi yang dapat dibagikan."],
    deliverables: ["Capability dan facility pages", "Product atau solution catalog", "Industry application", "Quality process dan dokumen valid", "Downloadable specification", "RFQ dan inquiry routing", "CMS serta multilingual option", "SEO foundation dan analytics"],
    proofs: [{ name: "Website Company Profile", detail: "Pendekatan Hammad Studio untuk trust, layanan, dokumen, dan inquiry perusahaan.", href: "/jasa-website-company-profile" }, { name: "Dashboard Custom", detail: "Kapabilitas sistem untuk katalog, workflow, role, dan data yang lebih spesifik.", href: "/solusi/perusahaan/sistem-custom-dashboard" }, { name: "ADD Logistik", detail: "Contoh penyusunan layanan dan inquiry untuk kebutuhan B2B.", href: "/work/add-logistik" }],
    faqs: companyFaqs,
    startingPrice: "Website manufaktur dimulai dari scope corporate website. Katalog, dokumen, multilingual, RFQ, dan integrasi dihitung berdasarkan kebutuhan.",
    proofLabel: "RELEVANT CAPABILITY",
    proofTitle: "Fondasi B2B yang dapat diterapkan secara jujur.",
    indexable: false,
  },
  konstruksi: {
    slug: "konstruksi",
    title: "Jasa Website Perusahaan Konstruksi dan Kontraktor",
    description: "Website kontraktor dan perusahaan konstruksi untuk profil, layanan, portofolio proyek, area kerja, dokumen, tender support, dan inquiry.",
    eyebrow: "WEBSITE KONSTRUKSI & KONTRAKTOR",
    hero: "Buat kapabilitas dan pengalaman proyek lebih mudah diverifikasi.",
    intro: "Website konstruksi perlu menyusun layanan, klasifikasi pekerjaan, portofolio, area operasi, metode kerja, keselamatan, dokumen valid, dan contact path untuk calon klien atau partner.",
    audience: "Untuk kontraktor, konsultan, supplier konstruksi, dan penyedia jasa proyek yang membutuhkan company profile digital serta presentasi project yang terstruktur.",
    outcomes: ["Layanan dan spesialisasi proyek lebih jelas.", "Portofolio dapat dipilah berdasarkan kategori.", "Dokumen valid tersedia pada konteks yang tepat.", "Inquiry tender atau partnership memiliki jalur yang jelas."],
    deliverables: ["Company dan capability profile", "Service hierarchy", "Project portfolio dan filters", "Area operasi", "Document downloads", "Tender atau inquiry form", "CMS project", "SEO foundation dan analytics"],
    proofs: [{ name: "Website Company Profile", detail: "Fondasi untuk profil, layanan, project, dokumen, dan inquiry perusahaan.", href: "/jasa-website-company-profile" }, { name: "Redesign Website", detail: "Pendekatan audit serta migrasi website perusahaan yang sudah tertinggal.", href: "/redesign-website" }, { name: "Buraq Logistik", detail: "Contoh presentasi coverage dan kapabilitas operasional B2B.", href: "/work/buraq-logistik" }],
    faqs: companyFaqs,
    startingPrice: "Website konstruksi dimulai dari scope company profile; jumlah project, CMS, dokumen, dan kebutuhan tender menentukan estimasi final.",
    proofLabel: "RELEVANT CAPABILITY",
    proofTitle: "Struktur corporate yang mendukung proses proyek.",
    indexable: false,
  },
  "ekspor-impor": {
    slug: "ekspor-impor",
    title: "Jasa Website Perusahaan Ekspor Impor",
    description: "Website perusahaan ekspor impor untuk komoditas atau produk, market coverage, proses, dokumen, logistics capability, dan inquiry internasional.",
    eyebrow: "WEBSITE EKSPOR IMPOR",
    hero: "Jelaskan produk, market, dan proses perdagangan lintas negara dengan percaya diri.",
    intro: "Website ekspor impor perlu menghubungkan katalog atau komoditas, origin, market coverage, proses, dokumentasi valid, logistics capability, dan inquiry dalam struktur yang mudah dipahami buyer internasional.",
    audience: "Untuk exporter, importer, trading company, supplier, dan distributor yang membutuhkan company profile bilingual atau multilingual serta inquiry B2B.",
    outcomes: ["Product dan market coverage tersaji jelas.", "Buyer dapat memahami proses serta dokumen yang tersedia.", "Website mendukung bahasa dan market yang dituju.", "Inquiry diarahkan dengan kebutuhan produk dan destination."],
    deliverables: ["Company dan trade profile", "Product atau commodity catalog", "Origin dan market coverage", "Process dan valid documents", "Multilingual architecture", "RFQ atau inquiry form", "Logistics capability", "SEO foundation dan analytics"],
    proofs: [{ name: "ADD Logistik", detail: "Contoh website B2B untuk layanan logistik dan kredibilitas perusahaan.", href: "/work/add-logistik" }, { name: "Buraq Logistik", detail: "Presentasi coverage, distribusi, trucking, dan kapabilitas operasional.", href: "/work/buraq-logistik" }, { name: "Website Logistik", detail: "Landing vertical untuk kebutuhan trucking, freight, dan distribusi.", href: "/industri/logistik" }],
    faqs: companyFaqs,
    startingPrice: "Website ekspor impor mengikuti scope corporate website. Multilingual, katalog, RFQ, dokumen, dan integrasi dihitung sesuai market serta workflow.",
    proofLabel: "RELEVANT CAPABILITY",
    proofTitle: "Fondasi B2B yang perlu dibuktikan dengan project langsung.",
    indexable: false,
  },
  distributor: {
    slug: "distributor",
    title: "Jasa Website Distributor dan Supplier B2B",
    description: "Website distributor dan supplier untuk menyusun kategori produk, area distribusi, brand principal, kapabilitas, dokumen, serta inquiry B2B.",
    eyebrow: "WEBSITE DISTRIBUTOR & SUPPLIER",
    hero: "Bantu buyer memahami produk, coverage, dan cara bekerja sama lebih cepat.",
    intro: "Website distributor perlu menjawab pertanyaan buyer dan partner secara efisien: produk apa yang tersedia, area mana yang dilayani, bagaimana proses permintaan, dokumen apa yang dapat diakses, dan siapa yang harus dihubungi.",
    audience: "Untuk distributor, supplier, trading company, dan bisnis B2B yang membutuhkan katalog terstruktur, coverage, dokumen, serta jalur request for quotation.",
    outcomes: ["Kategori produk dan layanan lebih mudah dinavigasi.", "Coverage dan kapabilitas distribusi terlihat jelas.", "Buyer dapat mengirim inquiry dengan konteks kebutuhan.", "Tim sales memiliki referensi resmi yang konsisten."],
    deliverables: ["Company dan capability profile", "Product atau brand catalog", "Coverage dan distribution network", "Document center sesuai kebutuhan", "RFQ atau inquiry routing", "CMS katalog", "Analytics dan conversion tracking", "SEO-ready foundation"],
    proofs: [{ name: "ADD Logistik", detail: "Website B2B yang menyusun layanan, coverage, kapabilitas, dan jalur inquiry.", href: "/work/add-logistik" }, { name: "Buraq Logistik", detail: "Presentasi trucking, distribusi regional, cakupan, dan kemampuan operasional.", href: "/work/buraq-logistik" }, { name: "Website Company Profile", detail: "Fondasi trust, layanan, project, dokumen, dan inquiry untuk perusahaan.", href: "/jasa-website-company-profile" }],
    faqs: companyFaqs,
    startingPrice: "Website distributor dimulai dari Website Rp 499 ribu atau CMS Rp 899 ribu. Katalog dan integrasi dihitung sesuai scope.",
    proofLabel: "RELEVANT CAPABILITY",
    proofTitle: "Struktur distributor yang belum diklaim sebagai case study.",
    indexable: false,
  },
  event: {
    slug: "event",
    title: "Jasa Website Event, Registrasi, dan Ticketing",
    description: "Website event untuk agenda, speaker, venue, sponsor, registrasi, database peserta, ticketing, QR check-in, dan pelaporan sesuai skala acara.",
    eyebrow: "WEBSITE & SISTEM EVENT",
    hero: "Dari pengumuman acara sampai peserta hadir di venue.",
    intro: "Kebutuhan event dapat berhenti pada halaman informasi atau berkembang menjadi registrasi, pembayaran, tiket digital, QR check-in, attendance dashboard, dan report. Scope dipilih sesuai alur acara—bukan semua fitur dipaksakan sejak awal.",
    audience: "Untuk seminar, workshop, kajian, conference, expo, festival, campaign, dan acara komunitas yang membutuhkan informasi serta pengelolaan peserta lebih rapi.",
    outcomes: ["Informasi acara dan CTA registrasi berada dalam satu journey.", "Data peserta tersimpan dan dapat dikelola sesuai scope.", "Ticketing serta check-in dapat ditambahkan ketika benar-benar dibutuhkan.", "Tim memiliki data registrasi, kehadiran, dan penjualan yang lebih terstruktur."],
    deliverables: ["Event information dan agenda", "Speaker, venue, sponsor, dan FAQ", "Registration form dan database peserta", "Admin dashboard dan export", "Payment serta ticket type sesuai paket", "Digital ticket dan QR check-in opsional", "Analytics dan social sharing", "SEO-ready foundation"],
    proofs: [{ name: "Masjid Raya Puri Telukjambe", detail: "Platform komunitas dengan informasi kegiatan, jadwal, livestream, donasi, dan pengelolaan fasilitas.", href: "/work/masjid-raya-puri-telukjambe" }, { name: "NaikLevel AI", detail: "Produk edukasi digital dengan landing, pembelian, pembayaran, dan konfirmasi.", href: "/work/naiklevel-ai" }, { name: "Harga Website", detail: "Ticketing mulai Rp 3,999 juta dengan payment, tiket digital, QR, scanner, dan attendance.", href: "/harga-website" }],
    faqs: companyFaqs,
    startingPrice: "Website mulai Rp 499 ribu untuk informasi event. Ticketing mulai Rp 3,999 juta untuk payment, QR, scanner, dan attendance.",
  },
} as const satisfies Record<string, ExpansionLanding>;
