import Link from "next/link";
import { ArrowLink, FAQ, Kicker, Marquee, PageHero, PricingGrid, Process, ProjectVisual, ServicesIndex } from "./ui";
import { localHref } from "@/lib/locale";
import { services, t } from "@/lib/site-data";
import { formatIDR } from "@/lib/estimator";
import type { Locale } from "@/lib/types";

export function HomePage({locale}:{locale:Locale}){
  const id=locale==="id";
  return <>
    <section className="home-hero"><Kicker>INDEPENDENT DIGITAL PRODUCT STUDIO — INDONESIA</Kicker><h1 className="hero-word"><span>Digital products,</span><span className="silver-text">engineered properly.</span></h1><div className="home-hero-bottom"><p>{id?"Website, commerce experience, business systems, dan software custom—dirancang dengan thoughtful, dibangun secara profesional, dan memiliki scope yang jelas sejak hari pertama.":"Websites, commerce experiences, business systems, and custom software—designed thoughtfully, engineered professionally, and scoped clearly from day one."}</p><div className="hero-actions"><ArrowLink href={localHref(locale,"/start-project")}>{id?"Mulai project":"Start a project"}</ArrowLink><ArrowLink muted href={localHref(locale,"/work")}>{id?"Lihat work":"View work"}</ArrowLink></div><div className="project-start">{id?"PROJECT DIMULAI DARI":"PROJECTS STARTING FROM"}<strong>Rp3.500.000</strong></div></div></section>
    <Marquee/>
    <section className="page-section"><div className="statement-grid"><h2>{id?<>Bisnis Anda tidak membutuhkan <span className="silver-text">website generik lagi.</span></>:<>Your business doesn’t need <span className="silver-text">another generic website.</span></>}</h2><p>{id?"Yang dibutuhkan adalah pengalaman digital yang berkomunikasi dengan jelas, membangun trust, dan memudahkan customer maupun tim untuk bertindak.":"It needs a digital experience that communicates clearly, builds trust, and makes it easier for customers and teams to act."}</p></div></section>
    <section className="page-section"><SectionHead index="01 / SELECTED WORK" title={id?"Work yang dipilih dengan sengaja.":"Selected with intent."} copy={id?"Portfolio launch hanya menampilkan project nyata. Slot visual ini siap diganti dengan empat case study dan screenshot asli.":"The launch portfolio will only show real projects. These visual slots are ready for four verified case studies and original screenshots."}/><div className="work-stack">{[1,2,3].map((n)=><article className="work-entry" key={n}><ProjectVisual index={n} title={n===1?"Systems / Operations":n===2?"Web / Commerce":"Products / Platforms"}/><div className="work-meta"><h3>{id?"Materi project segera hadir":"Project material pending"}</h3><p>{id?"Tidak ada client, outcome, atau testimonial yang direkayasa untuk mengisi portfolio.":"No clients, outcomes, or testimonials are fabricated to fill the portfolio."}</p><span>CASE STUDY / 0{n}</span></div></article>)}</div><ArrowLink href={localHref(locale,"/work")}>{id?"Lihat semua work":"View all work"}</ArrowLink></section>
    <section className="page-section"><SectionHead index="02 / CAPABILITIES" title={id?"Apa yang kami bangun.":"What we build."} copy={id?"Kami memilih solusi terkecil yang masuk akal untuk menyelesaikan problem sebenarnya—bukan menambahkan software tanpa alasan.":"We choose the smallest sensible solution for the actual problem—not more software for its own sake."}/><ServicesIndex locale={locale}/></section>
    <section className="page-section"><SectionHead index="03 / WHY HAMMAD" title={id?<>Studio kecil.<br/><span className="silver-text">Eksekusi serius.</span></>:<>Small studio.<br/><span className="silver-text">Serious execution.</span></>} copy={id?"Kolaborasi tetap direct. Lebih sedikit layer berarti komunikasi lebih jelas, keputusan lebih cepat, dan ownership lebih kuat.":"Collaboration stays direct. Fewer layers mean clearer communication, faster decisions, and stronger ownership."}/><Principles locale={locale}/></section>
    <section className="page-section"><SectionHead index="04 / PRICING" title={id?"Starting point yang jelas.":"Clear starting points."} copy={id?"Project berbeda membutuhkan scope berbeda. Bukan berarti harga harus menjadi rahasia.":"Different projects need different scopes. That doesn’t mean pricing needs to be a secret."}/><PricingGrid locale={locale} limit={3}/><div style={{marginTop:"3rem"}}><ArrowLink href={localHref(locale,"/pricing")}>{id?"Lihat semua pricing":"View full pricing"}</ArrowLink></div></section>
    <section className="page-section silver-section"><SectionHead index="05 / PROCESS" title={id?"Dari ide ke production.":"From idea to production."} copy={id?"Tidak menghilang selama enam minggu. Anda mendapat staging link, milestone preview, dan review checkpoint sepanjang project.":"No disappearing for six weeks. You get staging links, milestone previews, and review checkpoints throughout the project."}/><Process locale={locale}/></section>
    <section className="page-section"><SectionHead index="06 / QUESTIONS" title={id?"Sebelum kita mulai.":"Before we begin."}/><FAQ locale={locale}/></section>
  </>;
}

function SectionHead({index,title,copy}:{index:string,title:React.ReactNode,copy?:string}){return <div className="section-head"><Kicker>{index}</Kicker><div><h2>{title}</h2>{copy?<p>{copy}</p>:null}</div></div>}

function Principles({locale}:{locale:Locale}){const items=locale==="id"?[["Direct Collaboration","Anda berbicara langsung dengan orang yang memahami dan membangun product."],["Thoughtful Design","Keputusan visual dibuat dari brand, context, user, dan objective."],["Engineering Discipline","Performance, accessibility, security, dan maintainability adalah bagian dari build."],["Transparent Scope","Anda tahu apa yang dibuat, berapa investasinya, dan apa yang terjadi berikutnya."]]:[["Direct Collaboration","You work directly with people who understand and build the product."],["Thoughtful Design","Visual decisions come from brand, context, users, and objectives."],["Engineering Discipline","Performance, accessibility, security, and maintainability are part of the build."],["Transparent Scope","You know what is being built, what it costs, and what happens next."]];return <div className="principles">{items.map(([title,copy],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div>}

export function WorkPage({locale,project}:{locale:Locale,project?:string}){const id=locale==="id";if(project)return <><PageHero eyebrow="CASE STUDY / MATERIAL PENDING" title={id?"Case study yang jujur dimulai dari bukti nyata.":"An honest case study begins with real evidence."} body={id?"Template storytelling sudah siap. Client, context, challenge, strategy, solution, engineering, dan outcome akan dipublikasikan hanya setelah materi diverifikasi.":"The storytelling structure is ready. Client, context, challenge, strategy, solution, engineering, and outcome will only be published after the material is verified."}/><section className="page-section"><ProjectVisual title={project.replaceAll("-"," ")}/><div className="facts-grid"><Fact label="CLIENT" value="Pending"/><Fact label="SERVICE" value="Pending"/><Fact label="TIMELINE" value="Pending"/><Fact label="YEAR" value="2026"/></div><div className="content-prose"><h2>Context → Outcome</h2><p>{id?"Halaman ini sengaja tidak mengarang cerita project. Masukkan copy, visual, dan metrik asli ke content collection sebelum route diaktifkan untuk indexing.":"This page deliberately avoids inventing a project story. Add verified copy, visuals, and metrics to the content collection before enabling indexing."}</p></div></section></>;return <><PageHero eyebrow="WORK / SELECTED PROJECTS" title={id?<>Work dan <em>digital products.</em></>:<>Selected work and <em>digital products.</em></>} body={id?"Lebih baik sedikit case study yang kuat daripada puluhan screenshot tanpa konteks. Materi final akan dipilih berdasarkan kualitas dan relevansi.":"A few strong case studies are better than dozens of screenshots without context. Final material will be selected for quality and relevance."}/><section className="page-section"><div className="work-stack">{[1,2,3,4].map(n=><Link href={localHref(locale,`/work/project-${n}`)} className="work-entry" key={n}><ProjectVisual index={(n%3)+1} title={["Web / Presence","Commerce / Flow","Systems / Operations","Products / MVP"][n-1]}/><div className="work-meta"><h3>{id?"Project terverifikasi akan hadir di sini":"Verified project coming here"}</h3><p>CASE MATERIAL PENDING</p><span>0{n} / 04</span></div></Link>)}</div></section></>}

function Fact({label,value}:{label:string,value:string}){return <div className="fact"><span>{label}</span><strong>{value}</strong></div>}

export function ServicesPage({locale,slug}:{locale:Locale,slug?:string}){const id=locale==="id";const service=services.find(s=>s.slug===slug);if(service)return <><PageHero eyebrow={`SERVICES / ${t(service.name,locale).toUpperCase()}`} title={<><em>{t(service.headline,locale)}</em></>} body={t(service.description,locale)} aside={<><p className="kicker">{id?"MULAI":"STARTING AT"} / {formatIDR(service.startingPrice)}</p><ArrowLink href={localHref(locale,"/start-project")}>{id?"Diskusikan project":"Discuss your project"}</ArrowLink></>}/><section className="page-section"><SectionHead index="01 / DELIVERABLES" title={id?"Dibangun di sekitar kebutuhan nyata.":"Built around the real need."}/><div className="principles">{service.deliverables.map((item,i)=><article key={item.en}><span>0{i+1}</span><h3>{t(item,locale)}</h3><p>{id?"Scope detail dikonfirmasi melalui discovery dan dicatat jelas di proposal.":"Detailed scope is confirmed in discovery and documented clearly in the proposal."}</p></article>)}</div></section><section className="page-section silver-section"><SectionHead index="02 / DELIVERY" title={id?"Proses yang terlihat.":"A visible process."}/><Process locale={locale}/></section><section className="page-section"><SectionHead index="03 / FAQ" title={id?"Hal yang perlu diketahui.":"What to know."}/><FAQ locale={locale}/></section></>;return <><PageHero eyebrow="SERVICES / CAPABILITIES" title={id?<>Problem yang berbeda membutuhkan <em>product yang berbeda.</em></>:<>Different problems need <em>different products.</em></>} body={id?"Dari marketing site yang fokus sampai platform operasional, kami memilih solusi terkecil yang masuk akal untuk problem sebenarnya.":"From a focused marketing site to an operational platform, we choose the smallest sensible solution for the actual problem."}/><section className="page-section"><ServicesIndex locale={locale}/></section></>}
