import Link from "next/link";
import { ArrowLink, Kicker, ProjectVisual } from "./ui";
import { localHref } from "@/lib/locale";
import { services } from "@/lib/site-data";
import type { Locale } from "@/lib/types";

export function ReferenceHome({ locale }: { locale: Locale }) {
  const id = locale === "id";
  return <>
    <section className="ref-hero">
      <div className="ref-hero-orbit" aria-hidden />
      <div className="ref-hero-top"><Kicker>INDEPENDENT DIGITAL PRODUCT STUDIO / INDONESIA</Kicker><span className="ref-est">EST. 2026 / CLARITY FIRST</span></div>
      <div className="ref-hero-copy"><h1>{id ? <>Bangun dengan <em>niat.</em><br />Luncurkan dengan yakin.</> : <>Build with <em>intention.</em><br />Launch with confidence.</>}</h1><p>{id ? "Kami merancang website, commerce experience, business systems, dan software custom yang punya tujuan jelas sejak awal.":"We design websites, commerce experiences, business systems, and custom software with a clear purpose from the start."}</p></div>
      <div className="ref-hero-bottom"><ArrowLink href={localHref(locale,"/work")}>{id?"Lihat work":"Explore work"}</ArrowLink><ArrowLink muted href={localHref(locale,"/start-project")}>{id?"Mulai project":"Start a project"}</ArrowLink><span className="ref-scroll">SCROLL TO EXPLORE ↓</span></div>
    </section>
    <div className="ref-ribbon"><span>CLARIFY</span><i>✦</i><span>DESIGN</span><i>✦</i><span>ENGINEER</span><i>✦</i><span>EVOLVE</span><i>✦</i><span>CLARIFY</span><i>✦</i><span>DESIGN</span><i>✦</i><span>ENGINEER</span><i>✦</i><span>EVOLVE</span></div>
    <section className="ref-section ref-intro"><div className="ref-label"><Kicker>01 / THE STUDIO</Kicker></div><div><h2>{id?<>Digital yang baik terasa <span>jelas</span> sebelum terasa canggih.</>:<>Good digital work feels <span>clear</span> before it feels clever.</>}</h2><p>{id?"Hammad Studio membantu bisnis bergerak dari ide, proses manual, atau website generik menuju produk digital yang bisa digunakan, diukur, dan dikembangkan.":"Hammad Studio helps businesses move from ideas, manual processes, or generic websites toward digital products that can be used, measured, and evolved."}</p><ArrowLink href={localHref(locale,"/studio")}>{id?"Kenali studio":"Meet the studio"}</ArrowLink></div></section>
    <section className="ref-section"><div className="ref-section-head"><div className="ref-label"><Kicker>02 / SELECTED WORK</Kicker></div><div><h2>{id?"Beberapa hal yang kami bangun.":"A few things we build."}</h2><p>{id?"Portfolio tetap curated. Setiap project akan punya context, challenge, solution, dan outcome—bukan sekadar screenshot.":"The portfolio stays curated. Every project will carry context, challenge, solution, and outcome—not just screenshots."}</p></div></div><div className="ref-work-grid">{[1,2,3,4].map((n)=><Link className={n%2===0?"ref-work-card offset":"ref-work-card"} href={localHref(locale,`/work/project-${n}`)} key={n}><ProjectVisual index={(n%3)+1} title={["BUSINESS / WEB","COMMERCE / FLOW","SYSTEMS / OPS","PRODUCT / MVP"][n-1]}/><div><span>0{n} / CASE STUDY PENDING</span><h3>{id?"Materi project akan hadir":"Project material pending"}</h3></div></Link>)}</div><div className="ref-after-link"><ArrowLink href={localHref(locale,"/work")}>{id?"Buka selected work":"View selected work"}</ArrowLink></div></section>
    <section className="ref-section ref-services"><div className="ref-section-head"><div className="ref-label"><Kicker>03 / AREA OF EXPERTISE</Kicker></div><div><h2>{id?"Capabilities yang mengikuti ambisi.":"Capabilities shaped around ambition."}</h2><p>{id?"Services adalah output. Sistem dan outcome adalah yang sebenarnya kami bangun.":"Services are outputs. Systems and outcomes are what we actually build."}</p></div></div><div className="ref-service-stack">{services.map((service)=><Link href={localHref(locale,`/services/${service.slug}`)} key={service.slug}><span>{service.number}</span><h3>{service.name[locale]}</h3><p>{service.description[locale]}</p><b>↗</b></Link>)}</div></section>
    <section className="ref-section ref-silver"><div className="ref-section-head"><div className="ref-label"><Kicker>04 / HOW WE WORK</Kicker></div><div><h2>{id?"Proses yang terlihat. Keputusan yang jelas.":"A visible process. Clear decisions."}</h2><p>{id?"Tidak ada project yang menghilang di balik update yang samar.":"No project disappears behind vague updates."}</p></div></div><div className="ref-process"><article><span>01</span><h3>{id?"Pahami":"Understand"}</h3><p>{id?"Kami mendengar, memetakan problem, dan menentukan apa yang harus berubah.":"We listen, map the problem, and define what needs to change."}</p></article><article><span>02</span><h3>{id?"Bangun":"Design & Build"}</h3><p>{id?"Insight diterjemahkan menjadi experience yang thoughtful dan engineering yang solid.":"Insight becomes a thoughtful experience and disciplined engineering."}</p></article><article><span>03</span><h3>{id?"Kembangkan":"Refine & Evolve"}</h3><p>{id?"Release diperbaiki melalui penggunaan nyata, bukan asumsi semata.":"The release improves through real use, not assumptions alone."}</p></article></div></section>
    <section className="ref-section ref-fit"><div className="ref-label"><Kicker>05 / PROJECT FIT</Kicker></div><div><h2>{id?<>Kami bukan untuk <span>semua</span> project.</>:<>We’re not for <span>every</span> project.</>}</h2><p>{id?"Kami tidak mengejar kerja tercepat, harga termurah, atau unlimited revision tanpa arah. Kami cocok dengan tim yang peduli pada outcome, trust the process, dan ingin membangun sesuatu yang bisa dipakai.":"We don’t chase the fastest delivery, cheapest price, or endless revisions without direction. We work best with teams who care about outcomes and trust the process."}</p><ArrowLink href={localHref(locale,"/project-fit")}>{id?"Cek project fit":"Check project fit"}</ArrowLink></div></section>
    <section className="ref-section ref-final"><Kicker>06 / START A CONVERSATION</Kicker><h2>{id?<>Punya sesuatu yang layak <em>dibangun?</em></>:<>Have something worth <em>building?</em></>}</h2><ArrowLink href={localHref(locale,"/start-project")}>{id?"Mulai project":"Start a project"}</ArrowLink></section>
  </>;
}

export function ReferenceServices({ locale }: { locale: Locale }) {
  const id = locale === "id";
  return <><section className="ref-page-intro"><Kicker>03 / SERVICES</Kicker><h1>{id?<>Area of <em>expertise.</em></>:<>Area of <em>expertise.</em></>}</h1><p>{id?"Strategi, design, dan technology bekerja sebagai satu sistem—dengan scope dan outcome yang bisa dipahami.":"Strategy, design, and technology working as one system—with scope and outcomes everyone understands."}</p></section><section className="ref-section ref-services"><div className="ref-service-stack">{services.map((service)=><Link href={localHref(locale,`/services/${service.slug}`)} key={service.slug}><span>{service.number}</span><h3>{service.name[locale]}</h3><p>{service.description[locale]}</p><b>↗</b></Link>)}</div></section><section className="ref-section ref-silver"><div className="ref-section-head"><div className="ref-label"><Kicker>METHOD / 03 STEPS</Kicker></div><div><h2>{id?"Dari problem ke outcome.":"From problem to outcome."}</h2></div></div><div className="ref-process"><article><span>01</span><h3>{id?"Understand":"Understand"}</h3><p>{id?"Tentukan problem yang tepat sebelum menyentuh fitur.":"Define the right problem before touching features."}</p></article><article><span>02</span><h3>{id?"Design & Build":"Design & Build"}</h3><p>{id?"Buat keputusan visual dan teknis dengan alasan yang jelas.":"Make visual and technical decisions for clear reasons."}</p></article><article><span>03</span><h3>{id?"Refine & Evolve":"Refine & Evolve"}</h3><p>{id?"Perbaiki dari data penggunaan dan feedback yang nyata.":"Improve from real use and meaningful feedback."}</p></article></div></section></>;
}
