import { ProjectBriefForm } from "./project-brief";
import { ProjectEstimator } from "./estimator-tool";
import { ProjectFit } from "./project-fit";
import { ArrowLink, FAQ, Kicker, PageHero, PricingGrid, Process } from "./ui";
import { localHref } from "@/lib/locale";
import type { Locale } from "@/lib/types";

export const articleData = [
  { slug:"berapa-biaya-website-bisnis", category:"BUSINESS / WEB", id:"Berapa biaya website bisnis yang benar-benar layak?", en:"What should a serious business website cost?" },
  { slug:"kapan-butuh-sistem-custom", category:"SYSTEMS", id:"Kapan bisnis benar-benar membutuhkan sistem custom?", en:"When does a business actually need a custom system?" },
  { slug:"keluar-dari-spreadsheet", category:"OPERATIONS", id:"Memindahkan operasi dari spreadsheet dan WhatsApp.", en:"Moving operations beyond spreadsheets and WhatsApp." },
  { slug:"scope-mvp-yang-masuk-akal", category:"PRODUCT", id:"Apa yang seharusnya masuk ke MVP?", en:"What should an MVP actually include?" },
] as const;

export function PricingPage({locale}:{locale:Locale}){const id=locale==="id";return <><PageHero eyebrow="PRICING / CLEAR FROM DAY ONE" title={id?<>Tidak ada <em>mystery pricing.</em></>:<>No <em>mystery pricing.</em></>} body={id?"Jenis project yang umum memiliki starting price dan baseline scope yang jelas. Kebutuhan custom dihitung berdasarkan pekerjaan tambahannya.":"Common project types have public starting prices and defined baseline scopes. Custom requirements are quoted based on the additional work involved."} aside={<ArrowLink href={localHref(locale,"/estimate")}>{id?"Estimasi project":"Estimate your project"}</ArrowLink>}/><section className="page-section"><PricingGrid locale={locale}/></section><section className="page-section"><div className="section-head"><Kicker>COMMERCIAL / CLARITY</Kicker><div><h2>{id?"Clear scope. Clear ownership.":"Clear scope. Clear ownership."}</h2></div></div><div className="principles"><Info n="01" title={id?"Pembayaran":"Payment"} copy={id?"Project kecil: 50% kickoff, 50% sebelum launch. Project besar: 40/30/30 atau milestone billing.":"Small projects: 50% kickoff, 50% before launch. Larger projects: 40/30/30 or milestone billing."}/><Info n="02" title={id?"Third-party cost":"Third-party costs"} copy={id?"Domain, hosting berbayar, API, gateway fee, dan license diinformasikan sebelum digunakan.":"Domains, paid hosting, APIs, gateway fees, and licenses are disclosed before use."}/><Info n="03" title={id?"Ownership":"Ownership"} copy={id?"Setelah pembayaran selesai, custom source code dan akses utama menjadi milik client sesuai agreement.":"After final payment, custom source code and primary access belong to the client as agreed."}/><Info n="04" title={id?"Perubahan scope":"Scope changes"} copy={id?"Change request menunjukkan impact ke biaya dan timeline sebelum pekerjaan tambahan dimulai.":"Change requests show cost and timeline impact before additional work begins."}/></div></section><section className="page-section"><div className="section-head"><Kicker>FAQ / PRICING</Kicker><div><h2>{id?"Yang sering ditanyakan.":"Common questions."}</h2></div></div><FAQ locale={locale}/></section></>}

function Info({n,title,copy}:{n:string,title:string,copy:string}){return <article><span>{n}</span><h3>{title}</h3><p>{copy}</p></article>}

export function StudioPage({locale}:{locale:Locale}){const id=locale==="id";return <><PageHero eyebrow="STUDIO / INDEPENDENT BY DESIGN" title={id?<>Independen <em>karena pilihan.</em></>:<>Independent <em>by design.</em></>} body={id?"Hammad Studio hadir sebagai alternatif antara kerja freelance yang fragmented dan proses agency besar yang berat.":"Hammad Studio exists as an alternative between fragmented freelance work and heavyweight agency processes."}/><section className="page-section"><div className="statement-grid"><h2>{id?<>Premium tanpa <span className="silver-text">agency nonsense.</span></>:<>Premium without the <span className="silver-text">agency nonsense.</span></>}</h2><p>{id?"Premium datang dari taste, detail, reliability, engineering, dokumentasi, dan pengalaman client—bukan birokrasi atau sales theatre.":"Premium comes from taste, detail, reliability, engineering, documentation, and client experience—not bureaucracy or sales theatre."}</p></div></section><section className="page-section"><div className="section-head"><Kicker>01 / PRINCIPLES</Kicker><div><h2>{id?"Cara kami bekerja.":"How we work."}</h2></div></div><div className="principles"><Info n="01" title="Direct" copy={id?"Tidak ada account layer yang tidak memahami project.":"No account layer disconnected from the project."}/><Info n="02" title="Thoughtful" copy={id?"Design mengikuti context, bukan trend template.":"Design follows context, not template trends."}/><Info n="03" title="Disciplined" copy={id?"Engineering quality dimulai sebelum coding.":"Engineering quality begins before coding."}/><Info n="04" title="Owned" copy={id?"Dibangun untuk Anda. Dimiliki oleh Anda.":"Built for you. Owned by you."}/></div></section><section className="page-section silver-section"><div className="section-head"><Kicker>02 / PROCESS</Kicker><div><h2>{id?"Dari ide ke production.":"From idea to production."}</h2></div></div><Process locale={locale}/></section></>}

export function InsightsPage({locale,slug}:{locale:Locale,slug?:string}){const id=locale==="id";const selected=articleData.find(a=>a.slug===slug);if(selected)return <><PageHero eyebrow={`${selected.category} / INSIGHT`} title={<>{id?selected.id:selected.en}</>} body={id?"Catatan praktis dari design, engineering, dan pemahaman operasi bisnis.":"A practical note drawn from design, engineering, and understanding business operations."}/><article className="page-section"><div className="content-prose"><p>{id?"Keputusan digital yang baik dimulai dari memahami problem dan risikonya, bukan memilih teknologi atau daftar fitur terlebih dahulu.":"Good digital decisions begin with understanding the problem and its risks, not choosing technology or a feature list first."}</p><h2>{id?"Mulai dari outcome.":"Start with the outcome."}</h2><p>{id?"Tentukan perubahan yang harus terjadi setelah product digunakan. Apakah customer lebih mudah mengambil keputusan? Apakah admin berhenti memasukkan data yang sama dua kali? Apakah founder bisa menguji asumsi terpenting?": "Define what must change after the product is used. Can customers decide more easily? Does the team stop entering the same data twice? Can the founder test the most important assumption?"}</p><h2>{id?"Scope adalah keputusan bisnis.":"Scope is a business decision."}</h2><p>{id?"Scope yang baik bukan daftar semua hal yang mungkin dibuat. Scope adalah batas yang sengaja dipilih agar investasi, timeline, dan kualitas tetap rasional.":"Good scope is not a list of everything that could be built. It is a deliberate boundary that keeps investment, timeline, and quality rational."}</p><h2>{id?"Bangun, validasi, lalu perbaiki.":"Build, validate, then improve."}</h2><p>{id?"Release pertama harus cukup lengkap untuk melakukan tugas utamanya dengan baik, tetapi cukup fokus untuk dipelajari dari penggunaan nyata.":"The first release should be complete enough to do its primary job well, yet focused enough to learn from real use."}</p></div></article></>;return <><PageHero eyebrow="INSIGHTS / NOTES FROM THE STUDIO" title={id?<>Thinking di balik <em>digital products.</em></>:<>Thinking behind <em>digital products.</em></>} body={id?"Bukan SEO spam. Catatan tentang design, engineering, business systems, product, commerce, dan automation.":"Not SEO filler. Notes on design, engineering, business systems, product, commerce, and automation."}/><section className="page-section"><div className="article-list">{articleData.map((article,index)=><a className="article-row" href={localHref(locale,`/insights/${article.slug}`)} key={article.slug}><span>0{index+1}</span><h2>{id?article.id:article.en}</h2><p>{article.category} / 2026</p></a>)}</div></section></>}

export function ToolPage({locale,type}:{locale:Locale,type:"estimate"|"fit"|"brief"}){const id=locale==="id";if(type==="brief")return <><PageHero eyebrow="PROJECT BRIEF / ≈ 3 MIN" title={id?<>Ceritakan apa yang <em>ingin Anda bangun.</em></>:<>Tell us what <em>you’re building.</em></>} body={id?"Sedikit konteks membantu kami memahami project sebelum kita bicara.":"A little context helps us understand the project before we talk."}/><section className="page-section"><ProjectBriefForm locale={locale}/></section></>;if(type==="fit")return <><PageHero eyebrow="PROJECT FIT / 5 QUESTIONS" title={id?<>Apakah kita <em>cocok bekerja sama?</em></>:<>Are we a <em>good fit?</em></>} body={id?"Tidak setiap project membutuhkan Hammad Studio. Lima pertanyaan ini membantu menentukan kecocokan sebelum menghabiskan waktu di sales call.":"Not every project needs Hammad Studio. Five questions help determine fit before spending time on a sales call."}/><section className="page-section"><ProjectFit locale={locale}/></section></>;return <><PageHero eyebrow="PROJECT ESTIMATOR / BETA" title={id?<>Perkirakan <em>project Anda.</em></>:<>Estimate <em>your project.</em></>} body={id?"Pilih tipe, kompleksitas, dan capability. Anda akan mendapat range perencanaan—bukan angka palsu yang menyamar sebagai quotation final.":"Choose the type, complexity, and capabilities. You’ll get a planning range—not a false number pretending to be a final quotation."}/><section className="page-section"><ProjectEstimator locale={locale}/></section></>}

const seoCopy:Record<string,[string,string,string,string]>={
  "website-company-profile":["Website company profile yang tidak terasa template.","Company websites that do not feel templated.","Digital presence untuk membangun trust, menjelaskan offering, dan menghasilkan enquiry.","Digital presence designed to build trust, explain the offer, and generate enquiries."],
  "jasa-dashboard-admin":["Dashboard admin yang mengikuti operasi bisnis.","Admin dashboards built around real operations.","Satukan status, data, reporting, dan workflow tanpa menambah spreadsheet baru.","Bring status, data, reporting, and workflows together without adding another spreadsheet."],
  "custom-web-application":["Web application custom untuk workflow yang spesifik.","Custom web applications for specific workflows.","Software yang dibangun berdasarkan user, process, security, dan tujuan bisnis.","Software shaped by users, process, security, and business objectives."],
  "event-registration-platform":["Registration platform dari campaign sampai check-in.","Registration platforms from campaign to check-in.","Satukan registration, payment, QR ticket, participant access, dan operational dashboard.","Connect registration, payment, QR tickets, participant access, and operations."],
  "ecommerce-development":["Commerce experience yang berakhir pada transaksi.","Commerce experiences designed to complete transactions.","Katalog, checkout, payment, fulfillment, dan order management sesuai workflow bisnis.","Catalogue, checkout, payment, fulfillment, and order management aligned to the business."],
  "booking-system":["Booking system tanpa admin berulang.","Booking systems without repetitive administration.","Availability, scheduling, payment, notification, dan status dalam satu alur.","Availability, scheduling, payment, notifications, and status in one flow."],
  "payment-gateway-integration":["Payment gateway integration yang dirancang sebagai flow.","Payment gateway integration designed as a complete flow.","Bukan sekadar API: status pembayaran, callback, notification, reconciliation, dan failure state.","More than an API: payment states, callbacks, notifications, reconciliation, and failure handling."],
};

export function UtilityPage({locale,path}:{locale:Locale,path:string}){const id=locale==="id";if(seoCopy[path]){const copy=seoCopy[path];return <><PageHero eyebrow="SPECIALIZED CAPABILITY / INDONESIA" title={<>{id?copy[0]:copy[1]}</>} body={id?copy[2]:copy[3]} aside={<><p className="kicker">CLEAR SCOPE / CLEAR PRICING</p><ArrowLink href={localHref(locale,"/start-project")}>{id?"Diskusikan kebutuhan":"Discuss the project"}</ArrowLink></>}/><section className="page-section"><div className="section-head"><Kicker>APPROACH / OUTCOME</Kicker><div><h2>{id?"Dibangun untuk melakukan tugasnya.":"Built to do its job."}</h2><p>{id?"Discovery memetakan user, workflow, constraint, data, dan definition of done. Hasilnya adalah scope yang bisa dipahami sebelum implementation dimulai.":"Discovery maps users, workflows, constraints, data, and definition of done. The result is a scope everyone understands before implementation begins."}</p></div></div><Process locale={locale}/></section></>};if(path==="care")return <><PageHero eyebrow="STUDIO CARE / AFTER LAUNCH" title={id?<>Launch bukan <em>akhirnya.</em></>:<>Launch is not <em>the end.</em></>} body={id?"Technical maintenance, monitoring, support, dan improvement kecil dengan scope bulanan yang jelas. Mulai sekitar Rp500 ribu–Rp1,5 juta per bulan.":"Technical maintenance, monitoring, support, and small improvements with a clear monthly scope. Starting around Rp500K–Rp1.5M per month."}/><section className="page-section"><div className="principles"><Info n="01" title="Maintenance" copy="Dependencies, technical health, and preventive care."/><Info n="02" title="Monitoring" copy="Production availability and critical flow checks."/><Info n="03" title="Support" copy="Priority technical support within an agreed response window."/><Info n="04" title="Improve" copy="A defined allocation for small monthly improvements."/></div></section></>;if(path==="contact")return <section className="page-section"><div className="contact-panel"><h2>{id?<>Mari bicara tentang <span className="silver-text">apa yang Anda bangun.</span></>:<>Let’s talk about <span className="silver-text">what you’re building.</span></>}</h2><div className="contact-details"><Kicker>CONTACT / INDONESIA</Kicker><a href="mailto:hello@hammad.studio">hello@hammad.studio</a><p>{id?"Untuk scope yang lebih jelas, project brief adalah cara tercepat untuk memulai.":"For a clearer scope, the project brief is the fastest way to begin."}</p><ArrowLink href={localHref(locale,"/start-project")}>{id?"Mulai project":"Start a project"}</ArrowLink></div></div></section>;return <LegalPage locale={locale} type={path.includes("privacy")?"privacy":"terms"}/>}

function LegalPage({locale,type}:{locale:Locale,type:"privacy"|"terms"}){const id=locale==="id";const privacy=type==="privacy";return <><PageHero eyebrow={`LEGAL / ${type.toUpperCase()}`} title={privacy?(id?"Privasi Anda penting.":"Your privacy matters."):(id?"Ketentuan yang jelas.":"Clear terms.")} body={id?"Versi awal untuk transparansi website dan project enquiry. Review legal lokal tetap diperlukan sebelum production launch.":"An initial policy for website and project-enquiry transparency. Local legal review is still required before production launch."}/><section className="page-section"><div className="content-prose legal"><h2>{privacy?(id?"Data yang dikumpulkan":"Information we collect"):(id?"Penggunaan website":"Website use")}</h2><p>{privacy?(id?"Kami mengumpulkan informasi yang Anda kirim melalui project brief, termasuk kontak, konteks project, dan file referensi. Data digunakan untuk mengevaluasi dan menanggapi enquiry.":"We collect information submitted through the project brief, including contact details, project context, and reference files. It is used to evaluate and respond to enquiries."):(id?"Konten website bersifat informasional. Estimasi bukan quotation final dan engagement baru dimulai setelah proposal atau statement of work disetujui.":"Website content is informational. Estimates are not final quotations, and an engagement begins only after a proposal or statement of work is accepted.")}</p><h2>{id?"Third-party services":"Third-party services"}</h2><p>Neon, Cloudflare R2, Resend, Vercel, and Google Analytics may process limited information required to operate this website. Their respective policies apply.</p><h2>{id?"Kontak":"Contact"}</h2><p>Questions may be sent to hello@hammad.studio.</p></div></section></>}
